### ISSUE TITLE
run_training.py, shape problem

### ISSUE THREAD

**Issue by QendKrasniqi** [breizhn/DTLN#2] opened 2020-05-28 09:49 UTC
I'm trying to train a new model using run_training.py.
When I read my .wav files using `scipy.io.wavfile.read` I get a 2d array, something like the following.

`
[[ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 1  1], [ 2  2], [ 2  2], [ 2  2], [ 2  2], [ 3  3], [ 5  5], [ 6  6], [ 6  6], [ 5  5], [ 3  3], [ 3  3], [ 2  3], [ 3  3], [ 2  2], [ 1  1], [ 0  0], [ 0  0], [ 0  0], [ 1  1], [ 2  2], [ 2  2], [ 0  0], [-2 -3], [-5 -5], [-5 -5], [-2 -2], [ 0  0], [ 2  2], [ 3  3], [ 1  1], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 1  1], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 0  0], [ 1  1], [ 1  1], [ 2  2], [ 1  1], [ 0  0], [ 0  0], [ 0  0], [ 1  1], [ 2  2], [ 1  1], [ 0  0], [-1 -1], [-2 -2], [-2 -2], [-1 -1], [ 0  0], [ 1  1], [ 2  2], [ 2  2]]
`

When I run the script, I get the following error:

`
ValueError: generator yielded an element of shape (720000, 2) where an element of shape (720000,) was expected.
`

Full error message:

`
Traceback (most recent call last):
  File "/home/qendrim/solaborate/repos/ML/NoiseCancellation/DTLN/run_training.py", line 51, in <module>
    modelTrainer.train_model(runName, path_to_train_mix, path_to_train_speech, path_to_val_mix, path_to_val_speech)
  File "/home/qendrim/solaborate/repos/ML/NoiseCancellation/DTLN/DTLN_model.py", line 383, in train_model
    use_multiprocessing=True)
  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 632, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  ValueError: generator yielded an element of shape (720000, 2) where an element of shape (720000,) was expected.
Traceback (most recent call last):

  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 236, in __call__
    ret = func(*args)

  File "/home/qendrim/anaconda3/envs/solab-py37-tf2/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 825, in generator_py_func
    "of shape %s was expected." % (ret_array.shape, expected_shape))

ValueError: generator yielded an element of shape (720000, 2) where an element of shape (720000,) was expected.

 [[{{node PyFunc}}]]
[[IteratorGetNext]] [Op:__inference_distributed_function_10659]

Function call stack:
distributed_function
`

python: 3.7
tensorflow: 2.1

**Comment by breizhn** [comment] 2020-05-28 11:06
It looks like you are trying to load two channel .wav files. The training supports only single channel audio data. You can add a down mixing to single channel at the `audio_generator` after reading the audio files. I will add a test for single channel in the `audio_generator`.

Which training corpus are you using?

Just a tip for loading .wav files. Use the library `soundfile` or `librosa` to load audio data. They will convert your audio data directly to float numpy arrays. `scipy.io.wavfile.read` will return the values as in the .wav and this is often int data.

**Comment by QendKrasniqi** [comment] 2020-05-28 13:28
training corpus: 1.1 GB audio files

**Comment by breizhn** [comment] 2020-05-28 15:40
1.1 GB of Audio will not be enough for a well generalizing model. Use the guide in the Readme for training data preparation to get 500h of training data.

**Comment by breizhn** [comment] 2020-05-28 16:13
I will close this issue, because it's not a bug.

**Closed by breizhn** 2020-05-28 16:13 UTC
